
using AdventOfCode;

// Task1_1.ProcessFile();
// Task1_2.ProcessFile();
// Task2_1.ProcessFile();
// Task2_2.ProcessFile();
// Task3_1.ProcessFile();
// Task3_2.ProcessFile();
// Task4_1.ProcessFile();
// Task4_2.ProcessFile();
// Task6_1.ProcessFile();
Task6_2.ProcessFile();
// Task7_1.ProcessFile();
// Task7_2.ProcessFile();
// Task8_1.ProcessFile();
// Task8_2.ProcessFile();
// Task9_1.ProcessFile();
// Task9_2.ProcessFile();
// Task10_1.ProcessFile();
// Task10_2.ProcessFile();
// Task11.ProcessFile();
// Task12_2.ProcessFile();
// Task13_1.ProcessFile();
// Task13_2.ProcessFile();
// Task14_1.ProcessFile();
// Task14_2.ProcessFile();
// Task15_1.ProcessFile();
// Task15_2.ProcessFile();
// Task17_1_Try_DP.ProcessFile();
// Task17_1.ProcessFile();
// Task17_2.ProcessFile();
// Task18_1.ProcessFile();
// Task18_2.ProcessFile();
// Task19_1.ProcessFile();
// Task21_1.ProcessFile();
// Task23_1.ProcessFile();